USE [master]
GO

/****** Object:  Database [ResturantDB]    Script Date: 9/23/2022 4:06:34 PM ******/
CREATE DATABASE [ResturantDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ResturantDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ResturantDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ResturantDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ResturantDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ResturantDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ResturantDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ResturantDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ResturantDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ResturantDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ResturantDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ResturantDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ResturantDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ResturantDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ResturantDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ResturantDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ResturantDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ResturantDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ResturantDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ResturantDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ResturantDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ResturantDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ResturantDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ResturantDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ResturantDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ResturantDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ResturantDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ResturantDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ResturantDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ResturantDB] SET  MULTI_USER 
GO

ALTER DATABASE [ResturantDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ResturantDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ResturantDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ResturantDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ResturantDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ResturantDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ResturantDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ResturantDB] SET  READ_WRITE 
GO

